[tox]
envlist =
    py{37,38}-tornado{50,60}
    py39-tornado{50,60,656}
    py310-tornado{60,656}
    py{311,312,313,314}-tornado656

[testenv]
package = editable
deps =
    -r requirements-dev.txt
    tornado50: tornado==5.0
    tornado60: tornado==6.0
    tornado656: tornado==6.5.6
commands =
    python -m pytest {posargs:.}
