swagger: "2.0"
info:
  description: |
    {{ description }}
  version: "{{ version }}"
  title: {{ title }}
  {% if contact %}
  contact:
    name: {{ contact }}
  {% endif %}
host: {{ host }}
basePath: {{ base_path }}
{% if security_definitions %}
securityDefinitions:
{{ security_definitions|nesteddict2yaml }}
{% endif %}
paths:
